name: Test for eclipse plugin

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     path: code
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          path: test
          ref: test
      # - name: Set up JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'
      #     architecture: 'x64'
      #     cache: maven
      # - name: Configure GPG Key
      #   run: |
      #     echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
      #   env:
      #     GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      # - name: Build with Maven
      #   working-directory: code
      #   run: mvn --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean verify --file pom.xml
      - name: deploy
        working-directory: test
        run: |
          mkdir -p update-site/${GITHUB_REF##*/}/
          mkdir -p `cat version.txt`
          
