name: Test for eclipse plugin

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: code
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages
      - name: deploy
        working-directory: gh-pages
        run: |
          mkdir `cat ../code/version.txt`
          mv update-site/${GITHUB_REF##*/}/* `cat ../code/version.txt`
          cp -R ../code/target/repository/* ../code/target/*.zip update-site/${GITHUB_REF##*/}/
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Add latest update-site for branch ${GITHUB_REF##*/}"
          git push origin gh-pages --force
